name: Java CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 使用 Temurin 的早期访问版（EA）JDK 23
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'  # 指定 Java 23
          distribution: 'temurin'  # Eclipse Temurin 提供早期访问版本支持
          cache: 'maven'

      # 缓存 Maven 依赖
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # 运行 Maven 测试
      - name: Run Tests with Maven
        run: mvn clean test